name: Bug report
description: Report a reproducible defect in Bytefold.
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is wrong?
      placeholder: A concise defect description.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Deterministic steps to reproduce.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: runtime
    attributes:
      label: Runtime
      description: Node/Deno/Bun/Web and versions
      placeholder: Node 24.11.0
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Verification evidence
      description: Include `npm run check` output snippet and any failing test names.

